<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="row" style="margin-top:100px;">
    <main role="main" class="container">
      <div class="jumbotron">
        <h1>Page not found</h1>
        <h2 class="text-center">A pagina requisitada não existe!</h2>
        <p class="lead">Projeto de site intitucional construido com tecnologia php orientada a objetos</p>
        <a class="btn btn-lg btn-primary" href="#" role="button">Pra o infinito e alemmmmm!</a>
      </div>
    </main>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
