<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="row" style="margin-top:100px;">
    <main role="main" class="container">
      <div class="jumbotron">
       <h1>Page About</h1>
        <p class="lead">Projeto de site intitucional construido com tecnologia php orientada a objetos</p>
        <a class="btn btn-lg btn-primary" href="#" role="button">Pra o infinito e alemmmmm!</a>
      </div>
      <div class="container">
         <h2>Metas</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
         <hr><h2>Valores</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
         <hr><h2>Objetivos</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad omnis fuga quam voluptatem illum. Architecto pariatur totam magnam ea, repellendus eveniet soluta, sit nulla, iure ratione laborum suscipit est nobis!</p>
        <br><br><br><br>
      </div>
    </main>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
