<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="row" style="margin-top:100px;">
    <main role="main" class="container">
      <div class="jumbotron">
        <h1>Page contact</h1>
        <p class="lead">Projeto de site intitucional construido com tecnologia php orientada a objetos</p>
        <a class="btn btn-lg btn-primary" href="#" role="button">Pra o infinito e alemmmmm!</a>
      </div>
      <div class="container">
         <h2 class="text-center">Entre em contato imediatamente agora já neste instante!</h2>
          <p class="text-center">
              Liga pá nois!!!<br>
              <tel>
                  (12)12346789<br>
              </tel>
              <adress>
                  Rua: Infinita<br>
                  CEP: 124596879<br>
                  City: Los Angeles<br>
              </adress>
          </p>
          <form style="margin-bottom:100px;">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" id="nome" aria-describedby="emailHelp" placeholder="Nome">
    <small id="nome" name="nome" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control" id="email" placeholder="Seu email">
  </div>
  <div class="form-group">
    <label for="assunto">Assunto</label>
    <input type="text" name="assunto" class="form-control" id="assunto" placeholder="Título da mensagem">
  </div>
  <div class="form-group">
     <label for="mensagem">Mensagem</label>
      <textarea class="form-control" name="mensagem" id="mensagem" cols="30" rows="10"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
      </div>
    </main>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
